import { categoriesEnum } from "./category.enum";

export const categories = [
	{name: categoriesEnum.ORIGINALS, image: "Originals-Cover", size:8, count:12},
	{name: categoriesEnum.FANARTS, image: "Fanarts-Cover", size:4, count:9},
	{name: categoriesEnum.HANDS, image: "Hands-Cover", size:4, count:6},
	{name: categoriesEnum.SKETCHES, image: "Sketches-Cover", size:4, count:9},
	{name: categoriesEnum.CHALLENGES, image: "Challenges-Cover", size:4, count:7}
]; 

export const drawings = [
	{name:"Me",category:categoriesEnum.ORIGINALS},
	{name:"Dont-Go",category:categoriesEnum.HANDS},
	{name:"Broken",category:categoriesEnum.ORIGINALS},
	{name:"Sketch8",category:categoriesEnum.SKETCHES},
	{name:"Beastars",category:categoriesEnum.FANARTS},
	{name:"Demon-Slayer",category:categoriesEnum.FANARTS},
	{name:"Sketch5",category:categoriesEnum.SKETCHES},
	{name:"Promises",category:categoriesEnum.HANDS},
	{name:"DeviantArt-Birthday",category:categoriesEnum.CHALLENGES},
	{name:"Big3",category:categoriesEnum.FANARTS},
	{name:"RaquelTraveilIustration-challenge",category:categoriesEnum.CHALLENGES},
	{name:"Break-Up",category:categoriesEnum.HANDS},
	{name:"Forest",category:categoriesEnum.ORIGINALS},
	{name:"Sketch7",category:categoriesEnum.SKETCHES},
	{name:"Freak",category:categoriesEnum.ORIGINALS},
	{name:"Fresh",category:categoriesEnum.ORIGINALS},
	{name:"Fullmetal-Alchemist",category:categoriesEnum.FANARTS},
	{name:"Sketch6",category:categoriesEnum.SKETCHES},
	{name:"Hawks",category:categoriesEnum.FANARTS},
	{name:"Kiki's-Delivery",category:categoriesEnum.FANARTS},
	{name:"Kitty",category:categoriesEnum.ORIGINALS},	
	{name:"Sketch2",category:categoriesEnum.SKETCHES},
	{name:"My-Birthday",category:categoriesEnum.ORIGINALS},
	{name:"One-Touch",category:categoriesEnum.HANDS},
	{name:"My-Heart",category:categoriesEnum.ORIGINALS},
	{name:"Sketch9",category:categoriesEnum.SKETCHES},
	{name:"Nezuko",category:categoriesEnum.FANARTS},
	{name:"Safe",category:categoriesEnum.ORIGINALS},
	{name:"Sagittarius",category:categoriesEnum.ORIGINALS},
	{name:"Skullet",category:categoriesEnum.ORIGINALS},
	{name:"Star",category:categoriesEnum.ORIGINALS},	
	{name:"Sketch3",category:categoriesEnum.SKETCHES},
	{name:"Tomb-Raider",category:categoriesEnum.FANARTS},
	{name:"Together", category:categoriesEnum.HANDS},
	{name:"Spirited-Away",category:categoriesEnum.FANARTS},
	{name:"Sketch1",category:categoriesEnum.SKETCHES},
	{name:"SimplyBrandirenee-challenge",category:categoriesEnum.CHALLENGES},
	{name:"Tasia-challenge",category:categoriesEnum.CHALLENGES},
	{name:"MillkyPop-challenge",category:categoriesEnum.CHALLENGES},
	{name:"Last-Time",category:categoriesEnum.HANDS},
	{name:"RossDraw-challenge",category:categoriesEnum.CHALLENGES},
	{name:"XephiaArt-challenge",category:categoriesEnum.CHALLENGES},
	{name:"Sketch4",category:categoriesEnum.SKETCHES}
];